<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// Scores sent by the cabinets (docs/DECISIONS.md D6, D50). Only personal
// bests are stored: a score that does not beat the player's best on the game
// is answered `not_improved` and dropped.
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('scores', function (Blueprint $table) {
            $table->id();
            // Generated by the cabinet: the idempotency key of its resends.
            $table->uuid('uuid')->unique();
            $table->foreignId('player_id')->constrained()->restrictOnDelete();
            $table->foreignId('game_id')->constrained()->restrictOnDelete();
            $table->foreignId('client_id')->constrained()->restrictOnDelete();
            $table->foreignUuid('client_startup_id')->nullable()->constrained()->nullOnDelete();
            // mhiex table: `default`, or another one some games keep.
            $table->string('table', 32)->default('default');
            $table->unsignedBigInteger('score');
            $table->unsignedSmallInteger('rank_on_cabinet')->nullable();
            $table->timestampTz('achieved_at');
            $table->timestampTz('received_at');
            // Moderation: a hidden score leaves the leaderboards and personal bests.
            $table->timestampTz('hidden_at')->nullable();

            $table->index(['game_id', 'table', 'player_id', 'score']);
            $table->index(['player_id', 'game_id']);
            $table->index('client_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('scores');
    }
};
