<?php

namespace App\Models;

use Database\Factories\ScoreFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * A personal best sent by a cabinet (docs/DECISIONS.md D6, D50).
 *
 * @property int $id
 * @property string $uuid Generated by the cabinet, idempotency key.
 * @property int $player_id
 * @property int $game_id
 * @property int $client_id
 * @property string|null $client_startup_id
 * @property string $table
 * @property int $score
 * @property int|null $rank_on_cabinet
 * @property Carbon $achieved_at
 * @property Carbon $received_at
 * @property Carbon|null $hidden_at
 * @property-read Player $player
 * @property-read Game $game
 * @property-read Client $client
 */
class Score extends Model
{
    /** @use HasFactory<ScoreFactory> */
    use HasFactory, HasUuids;

    public const DEFAULT_TABLE = 'default';

    public $timestamps = false;

    protected $attributes = [
        'table' => self::DEFAULT_TABLE,
    ];

    /**
     * HasUuids fills the public `uuid` column, not the primary key.
     *
     * @return list<string>
     */
    public function uniqueIds(): array
    {
        return ['uuid'];
    }

    protected function casts(): array
    {
        return [
            'score' => 'integer',
            'rank_on_cabinet' => 'integer',
            'achieved_at' => 'datetime',
            'received_at' => 'datetime',
            'hidden_at' => 'datetime',
        ];
    }

    /** @return BelongsTo<Player, $this> */
    public function player(): BelongsTo
    {
        return $this->belongsTo(Player::class);
    }

    /** @return BelongsTo<Game, $this> */
    public function game(): BelongsTo
    {
        return $this->belongsTo(Game::class);
    }

    /** @return BelongsTo<Client, $this> */
    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    /** @return BelongsTo<ClientStartup, $this> */
    public function startup(): BelongsTo
    {
        return $this->belongsTo(ClientStartup::class, 'client_startup_id');
    }

    /**
     * @param  Builder<self>  $query
     */
    public function scopeVisible(Builder $query): void
    {
        $query->whereNull('hidden_at');
    }

    public function isHidden(): bool
    {
        return $this->hidden_at !== null;
    }

    public function hide(): void
    {
        $this->forceFill(['hidden_at' => now()])->save();
    }

    public function unhide(): void
    {
        $this->forceFill(['hidden_at' => null])->save();
    }
}
